version: "3.8"

services:
  app:
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BRANCH_TAG}
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BRANCH_TAG}
    container_name: go_scraper_web
    ports:
      - "${PORT}:8080"
    environment:
      - APP_NAME
      - APP_ADDR
      - APP_RUN_MODE=prod
      - DB_CONNECTION
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE
    stdin_open: true
    tty: true
