version: "3.8"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - APP_NAME
      - APP_ADDR
      - APP_RUN_MODE=prod
      - DB_CONNECTION
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE
    depends_on:
      - database

  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
