version: "3.8"

services:
  database:
    image: postgres:12
    container_name: go_scraper_db_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_scraper_test
    ports:
      - "5433:5432"
