version: "3.8"

services:
  database:
    image: postgres:12
    container_name: go_scraper_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_scraper_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.0
    container_name: go_scraper_redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
