version: "3.8"

services:
  database_test:
    image: postgres:12
    container_name: go_scraper_db_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_scraper_test
    ports:
      - "5433:5432"

  redis_test:
    image: redis:6.2.0
    container_name: go_scraper_redis_test
    ports:
      - "6380:6379"
