version: "3.8"

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
