FROM golang:1.15-alpine as go-builder

ENV GO111MOD=on \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64

WORKDIR /app/workers

COPY . .

RUN go mod download

RUN go build

ENTRYPOINT ["/app/workers/workers"]
